it('fails', () => {
  throw new Error('Failed!!')
})
